version: '3.7'
services:
  redpanda:
    image: docker.vectorized.io/vectorized/redpanda:v21.9.5
    container_name: redpanda
    command:
     - redpanda start
     - --overprovisioned
     - --smp 1
     - --memory 1G
     - --reserve-memory 0M
     - --node-id 0
     - --check=false
     - --kafka-addr 0.0.0.0:9092
     - --advertise-kafka-addr redpanda:9092
     - --pandaproxy-addr 0.0.0.0:8082
     - --advertise-pandaproxy-addr redpanda:8082
    environment:
      - AUTO_CREATE_TOPICS_ENABLED=true
    ports:
     - 9092:9092
     - 8081:8081
     - 8082:8082
  data-generator:
    build: ./data-generator
    image: data-generator:latest
    container_name: data-generator
    depends_on:
      - redpanda
    labels:
      ofelia.enabled: "false"
      ofelia.job-exec.app.schedule: "@every 60s"
      ofelia.job-exec.app.command: "python -u ./twitch_kafka_producer.py"
  materialized:
    image: materialize/materialized:v0.12.0
    container_name: materialized
    command: -w1 --disable-telemetry
    ports:
      - 6875:6875
  mzcli:
    image: materialize/cli
    container_name: mzcli
  postgres:
    image: postgres:11-alpine
    container_name: postgres
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
    volumes:
     - ${PWD}/postgres-image:/docker-entrypoint-initdb.d
  metabase:
    image: iwalucas/metabase
    container_name: metabase
    depends_on:
       - materialized
    ports:
      - 3030:3000
    environment:
      - MB_PLUGINS_DIR=/app/plugins
    volumes:
     - ${PWD}/metabase-image/:/app/plugins
  ofelia:
    image: mcuadros/ofelia:latest
    container_name: ofelia
    depends_on:
      - data-generator
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
